name: Publish Mods

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      pack-base:
        type: boolean
        required: true
        default: false
      pack-light:
        type: boolean
        required: true
        default: false
      pack-hard:
        type: boolean
        required: true
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4

      - name: Pack base
        if: inputs.pack-base
        uses: ./.github/workflows/publish-mod.yml
        with:
          mod: base

      - name: Pack hard
        if: inputs.pack-hard
        uses: ./publish-mod.yml
        with:
          mod: hard

      - name: Pack light
        if: inputs.pack-light
        uses: ./publish-mod.yml
        with:
          mod: light
