name: Publish Mods

on:
  workflow_dispatch:
    inputs:
      pack-base:
        type: boolean
        required: true
        default: false
      # pack-light:
      #   type: boolean
      #   required: true
      #   default: false
      pack-hard:
        type: boolean
        required: true
        default: false

jobs:
  publish-base:
    if: inputs.pack-base
    uses: ./.github/workflows/publish-mod.yml
    with:
      mod: base
    secrets: 
      token: ${{ secrets.THUNDERSTORE }}
  
  publish-hard:
    if: inputs.pack-hard
    uses: ./.github/workflows/publish-mod.yml
    with:
      mod: hard
    secrets: 
      token: ${{ secrets.THUNDERSTORE }}

  # publish-light:
  #   if: inputs.pack-light
  #   uses: ./.github/workflows/publish-mod.yml
  #   with:
  #     mod: light
    # secrets: 
    #   token: ${{ secrets.THUNDERSTORE }}
